CREATE DATABASE logindb;

USE logindb;

CREATE TABLE Admin (
IdAdmin CHAR (12) NOT NULL PRIMARY KEY,
NamaAdmin VARCHAR (30) NOT NULL,
PasAdmin VARCHAR (12) NOT NULL,
username VARCHAR (30) NOT NULL,
TanggalLahir DATE
) ENGINE = INNODB;

CREATE TABLE UkmKomunitas (
IdUkmKomunitas CHAR (12) NOT NULL PRIMARY KEY,
NamaUkmKomunitas VARCHAR (30) NOT NULL,
PasUkmKomunitas VARCHAR (12) NOT NULL,
username VARCHAR (30) NOT NULL,
TanggalLahir DATE
) ENGINE = INNODB;

CREATE TABLE Mahasiswa (
NPM CHAR (12) NOT NULL PRIMARY KEY,
NamaMahasiswa VARCHAR (30) NOT NULL,
PasMhs VARCHAR (12) NOT NULL,
usernmae VARCHAR (30) NOT NULL,
TanggalLahir DATE
) ENGINE = INNODB;

CREATE TABLE Kegiatan (
Kegiatan VARCHAR (20) NOT NULL,
NamaKegiatan VARCHAR (50) NOT NULL,
NamaPenyelenggara VARCHAR (20) NOT NULL,
CONSTRAINT fk_NamaKegiatan PRIMARY KEY (NamaKegiatan)
) ENGINE = INNODB;

CREATE TABLE MinatdanBakat (
IdMinatdanBakat VARCHAR (50) NOT NULL PRIMARY KEY,
IdAdmin CHAR (12) NOT NULL,
NamaKegiatan VARCHAR (50) NOT NULL,
NPM CHAR (12) NOT NULL,
NamaMahasiswa VARCHAR (30) NOT NULL,
IdUkmKomunitas CHAR (12) NOT NULL,
NamaUkmKomunitas VARCHAR (30) NOT NULL,
) ENGINE = INNODB;

INSERT INTO Admin VALUES
('161060002', 'asia', '1997-02-03');
INSERT INTO Admin VALUES
('161060011', 'cindy', '1998-12-12');

INSERT INTO UKM VALUES
('161060017', 'melita', '1997-12-13');
INSERT INTO UKM VALUES
('161060001', 'ami', '1996-07-08');

SELECT * FROM Admin ;
SELECT * FROM UKM ;


